spring:
  application:
    name: toy
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true # H2 web ui
      path: /h2-console

jwt:
  secret: toy-secret-key
  expiration: 3600 # seconds(=1hour)